feat: allow reading multiple files for RDFReader
UUDigitalHumanitieslab/ianalyzer-readers pull request #21
Opened 2024-07-24 14:51 UTC by BeritJanssen

Close #20 : this branch adds the functionality by which the `RDFReader` can read multiple files, combine them into one graph, and then read out the relevant data per subject.

This requires some wrangling of the `Reader` class, i.e., instead of a `str` (filepath), the `source2dict` method now expects a source argument of type `Subject`. The `sources` property is overridden on the `RDFReader` class now to pass out subjects.

2024-07-25 12:14 UTC, lukavdplas requested changes
I have to say I disagree with the approach here.

At present, all readers follow the following structure:

1. Select files with `sources()`
2. Convert each source to an internal representation - implemented by the XMLReader/CSVReader/etc classes
3. Iterate over the source data to get document entries.
4. For each entry, extract the value per field.

This shared structure makes it easier to work with multiple reader types. Restructuring it so `sources()` becomes reponsible for steps 1-3 is an inconsistency that makes the package harder to grasp. It also violates the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), which is a useful principle for maintaining sanity across subclasses.

It seems like the issue here is that a "source" can be a collection of files, rather than a single file. This isn't how the `Source` type is currently defined, so that should be adjusted. But this isn't really a challenge to the overall paradigm of how readers work; the steps I mention above are still happening in this implementation, so why restructure it?

Changing the nature of `sources()` could be justifiable in a scenario where that function isn't needed or applicable. (Though in that case, I would recommend skipping the method rather than substituting it.) But this version ends up with a method `file_selector()` which takes over that function more or less exactly. This indicates that `sources()` shouldn't have been substituted at all, because its original function is still needed.

Some thoughts on alternative solutions:

For consistency, you could consider a format similar to the XMLReader, where the output yielded by sources can include a secondary file. This is done by adding the second file in the metadata dict as `'external_file'`. So in that case, `sources()` is kept as-is, but 

That format makes sense if it's used in a way somewhat similar to the XMLReader, where you have a "main" file with the nodes for your documents, and some additional files with data on related subjects.

However, the reader will end up taking the union of the graphs anyway, so functionally, there wouldn't a distinction between a "main" and "secondary" file. So it probably makes more sense to let each source be a list of filenames.

Side note: you've left out documentation updates in this PR. Since it's proposing a change to some core concepts, this would actually require a pretty major rewrite of the documentation. (Either to reframe everything consistently, or to add "except for the RDFReader" everywhere.)

2024-07-25 12:14 UTC, lukavdplas commented on ianalyzer_readers/readers/rdf.py
> +        return files
Other reader classes like XMLReader don't implement file selection, and leave that to the child class. It's a design decision whether or not readers should include "default behaviour" for this; there are good arguments for either side, I think.

However, whatever decision is made here, it makes sense to make it consistently across readers. I don't see a reason why the RDFReader should behave differently from, say, the XMLReader in this respect. If you want update the package so all readers should include a default assumption of file structure, I would be open to that, but it's a separate issue.

2024-07-25 14:14 UTC, lukavdplas commented
> it does make much more sense to think of sources as subjects / nodes. 

Hm, I don't really agree. Normally, a source is the container for the information you want to process. A node by itself doesn't contain any information, it's just an identifier. (Unless it's a Literal, but that seems like an unusual case here.) The actual information structure is the graph.

I think this analogy holds up:

| XML | CSV | RDF |
|-----|-----|-----|
| XML file | CSV file | RDF file(s) |
| BeautifulSoup tree | DictReader rows | Graph |
| tags matching query | iterated chunks of rows | nodes matching query |

An RDF node isn't really a "source", but rather an identifier for a location in a source. This implementation gets around that by storing the parsed graph as a side effect; so the data yielded by `sources()` doesn't need to contain the actual source of information you'll be extracting relationships from.

> The external_file approach was awkward and will not become less so if I take the same approach here.

Fair enough :)

> That being said, while I was busy with this branch, I asked myself whether there wouldn't be more cases where we need the option to read document-specific data from other files.

Yes, I was thinking the same thing when I was working on the XML reader. I think it's less essential for CSV/XML files (which are often self-contained), but these cases definitely happen.

I don't really have a clear sense of how to go about this, though. There is a risk that each case is so unique that we can't really provide useful handholds.

> This might actually also be a simple, no-op solution here: change the documentation to tell users that they should combine different .rdf files into one. 🤔

It could be. It's a bit inefficient if you have to parse files, take the union of the graphs, export it as a file, and then have the reader parse the exported file.

Perhaps the reader could include a method like `graph_from_source`, which will normally parse a single file, but you could override it to add extra graphs to it. That way, you can skip the export-import step. You might write something like this:

```python
class MyRDFReader(RDFReader):
	def graph_from_source(self, source):
		g1 = super().graph_from_source(source)
		g2 = super().graph_from_source(self.data_directory + 'more_data.ttl')
		g3 = super().graph_from_source(self.data_directory + 'even_more_data.ttl')
		return g1 + g2 + g3
```

2024-08-08 13:18 UTC, closed without merging

2024-08-08 13:52 UTC, BeritJanssen commented
I like the `graph_from_source` suggestion!